create schema api;

create table api.todos
(
  id   int primary key generated by default as identity,
  done boolean not null default false,
  task text    not null,
  due  timestamptz
);

insert into api.todos (task)
values ('finish tutorial 0'),
       ('pat self on back');

create role fusion_web_anon nologin;

grant usage on schema api to fusion_web_anon;
grant select on api.todos to fusion_web_anon;

-- Don't reset the authenticator password!
-- create role fusion_authenticator noinherit login password 'password';
grant fusion_web_anon to fusion_authenticator;

create role fusion_user nologin;
grant fusion_user to fusion_authenticator;

grant usage on schema api to fusion_user;
grant all on api.todos to fusion_user;

-- ----- Create the Users table ----- --
-- ---------------------------------- --
